version: '3.8'

services:
  # NestJS Backend приложение
  nestjs-backend:
    image: monday8888/backend:backend
    container_name: nestjs-education-backend
    env_file:
      - .env
    environment:
      # Основные настройки
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-8000}
      HOST: ${HOST:-0.0.0.0}
      APP_URL: ${APP_URL:-https://neuronest.pp.ua}
      
      # API и CORS настройки
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-https://neuronest.pp.ua,https://www.neuronest.pp.ua}
      API_PREFIX: ${API_PREFIX:-api}
      
      # Swagger настройки  
      SWAGGER_ENABLED: ${SWAGGER_ENABLED:-true}
      SWAGGER_PATH: ${SWAGGER_PATH:-api/docs}
      
      # MongoDB
      MONGODB_URI: ${MONGODB_URI}
      
      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-12h}
      
      # Email настройки
      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_SECURE: ${EMAIL_SECURE:-false}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-Education Platform}
      
      # Дополнительные настройки
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      
    volumes:
      # Постоянное хранение загруженных файлов
      - nestjs_uploads:/app/uploads
      - nestjs_temp:/app/temp
      - nestjs_logs:/app/logs
    restart: always
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/${API_PREFIX:-api}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Убираем expose портов наружу, только внутри сети
    expose:
      - "${PORT:-8000}"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:nginx:monday8888/proxi:prxoi
    container_name: nestjs-nginx-proxy
    volumes:
      # Конфигурация Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # SSL сертификаты (создайте папку и разместите сертификаты)
      - ./nginx/ssl:/etc/nginx/ssl:ro
      # Статические файлы фронтенда (если есть)
      - ./frontend:/usr/share/nginx/html:ro
      # Логи Nginx (создайте папку локально)
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    depends_on:
      - nestjs-backend
    restart: always
    networks:
      - app_network

volumes:
  nestjs_uploads:
    driver: local
  nestjs_temp:
    driver: local
  nestjs_logs:
    driver: local

networks:
  app_network:
    driver: bridge