version: '3.8'

services:
  # NestJS Backend приложение
  nestjs-backend:
    image: your-dockerhub-username/nestjs-education-platform:latest
    container_name: nestjs-education-backend
    environment:
      # Основные настройки
      NODE_ENV: production
      PORT: 8000
      APP_URL: https://neuronest.pp.ua
      
      # MongoDB
      MONGODB_URI: "mongodb+srv://troyant64:msfA0CqyZhkdF5NH@cluster0.icbj0hf.mongodb.net/"
      
      # JWT
      JWT_SECRET: "cd2c18d6c7f64a37a1a404c4d4c5a75ee76ec2b13949e3a67e1e0e1a3cf6a8db"
      JWT_EXPIRES_IN: "12h"
      
      # Email
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: 587
      EMAIL_SECURE: "false"
      EMAIL_USER: "test.dpoff@gmail.com"
      EMAIL_PASSWORD: "lplj ubop uudh fpjg"
      EMAIL_FROM: "test.dpoff@gmail.com"
      EMAIL_FROM_NAME: "Education Platform"
      
      # CORS для фронтенда
      CORS_ORIGIN: "https://neuronest.pp.ua"
      CORS_METHODS: "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"
      CORS_CREDENTIALS: "true"
      
      # Дополнительные настройки
      MAX_FILE_SIZE: 10485760
      SWAGGER_ENABLED: "true"
      
    volumes:
      # Постоянное хранение загруженных файлов
      - nestjs_uploads:/app/uploads
      - nestjs_temp:/app/temp
      - nestjs_logs:/app/logs
    restart: always
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Убираем expose портов наружу, только внутри сети
    expose:
      - "8000"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:nginx:monday8888/proxi:prxoi
    container_name: nestjs-nginx-proxy
    volumes:
      # Конфигурация Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # SSL сертификаты (создайте папку и разместите сертификаты)
      - ./nginx/ssl:/etc/nginx/ssl:ro
      # Статические файлы фронтенда (если есть)
      - ./frontend:/usr/share/nginx/html:ro
      # Логи Nginx (создайте папку локально)
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    depends_on:
      - nestjs-backend
    restart: always
    networks:
      - app_network

volumes:
  nestjs_uploads:
    driver: local
  nestjs_temp:
    driver: local
  nestjs_logs:
    driver: local

networks:
  app_network:
    driver: bridge