# docker-compose.prod.yml
version: '3.8'

services:
  nestjs-backend:
    image: nestjs-backend:production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      # Основные настройки
      - NODE_ENV=production
      - PORT=8000
      - APP_URL=https://nestneroyln.pp.ua #TODO
      
      # MongoDB (внешняя база данных)
      - MONGODB_URI=mongodb+srv://troyant64:msfA0CqyZhkdF5NH@cluster0.icbj0hf.mongodb.net/
      
      # Email настройки
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=test.dpoff@gmail.com
      - EMAIL_FROM=test.dpoff@gmail.com
      
      # CORS
      - CORS_ORIGINS=https://nestneroyln.pp.ua #TODO
    
    # Docker Secrets
    secrets:
      - jwt_secret
      - email_password
    
    # Сеть
    networks:
      - nestjs-network
    
    # Перезапуск
    restart: unless-stopped
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Ресурсы
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

# Сети
networks:
  nestjs-network:
    driver: bridge

# Секреты (для локального тестирования)
secrets:
  jwt_secret:
    file: ./secrets/jwt-secret.txt
  email_password:
    file: ./secrets/email-password.txt